# --- !Ups

create table "employees" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "first_name" varchar not null,
  "last_name" varchar not null,
  "job_title" varchar not null
);

INSERT INTO "employees" ("first_name", "last_name", "job_title") VALUES ('Hans', 'Schmidt', 'Boss');
INSERT INTO "employees" ("first_name", "last_name", "job_title") VALUES ('Katrin', 'Baecker', 'Entscheiderin');
INSERT INTO "employees" ("first_name", "last_name", "job_title") VALUES ('Paul', 'Kaiser', 'Ueberzeuger');
INSERT INTO "employees" ("first_name", "last_name", "job_title") VALUES ('Michael', 'Lahm', 'Ausfuehrer');


# --- !Downs

drop table "employees" if exists;
